# Generated by Django 4.0.4 on 2022-05-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.TextField()),
                ('companyname', models.TextField()),
                ('yearsofexp', models.TextField()),
                ('location', models.TextField()),
                ('JobDescp', models.TextField()),
                ('salary', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
